--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/name: kine-ui-register
    app.kubernetes.io/part-of: kine-ui-register
    app.kubernetes.io/version: latest
  name: kine-ui-register
spec: 
  ports: 
    - 
      name: http
      port: 8000
      targetPort: 80
  selector: 
    app.kubernetes.io/name: kine-ui-register
    app.kubernetes.io/part-of: kine-ui-register
    app.kubernetes.io/version: latest
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations: 
    deployment.kubernetes.io/revision: "3"
  labels: 
    app.kubernetes.io/name: kine-ui-register
    app.kubernetes.io/part-of: kine-ui-register
    app.kubernetes.io/version: latest
  name: kine-ui-register
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app.kubernetes.io/name: kine-ui-register
      app.kubernetes.io/part-of: kine-ui-register
      app.kubernetes.io/version: latest
  template: 
    metadata: 
      labels: 
        app.kubernetes.io/name: kine-ui-register
        app.kubernetes.io/part-of: kine-ui-register
        app.kubernetes.io/version: latest
    spec: 
      containers: 
        - 
          env: 
            - 
              name: KUBERNETES_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
          image: kine-ui-register:latest
          imagePullPolicy: Never
          name: kine-ui-register
          ports: 
            - 
              containerPort: 3000
              name: http
              protocol: TCP

